### PR TITLE
fix: iterable equality comparisons

### LINKED ISSUE #101: Equatable doesn't work with nested custom Iterable objects
**Describe the bug**
Equatable doesn't work with class that override `iterator` like so:

**To Reproduce**
```dart
class SomeObject with EquatableMixin {
  final CustomList list;

  const SomeObject(this.list);

  @override
  List<Object> get props => [list];
}

class CustomList extends Iterable<String> with EquatableMixin {
  final bool flag;
  final List<String> list;

  const CustomList({this.list, this.flag});

  @override
  List<Object> get props => [flag, list];

  @override
  Iterator<String> get iterator => list.iterator;
}
```

```dart
const list1 = CustomList(list: ['1', '2'], flag: true);
const list2 = CustomList(list: ['1', '2'], flag: false);

print(const SomeObject(list1) == const SomeObject(list2)); // true
```

**Additional context**
As a partial solution, if the object inherits from the `Equatable`, then compare via `==`

### PR DESCRIPTION
**Pull request by felangel**
## Status
**READY**

## Breaking Changes
NO

## Description
- fix: iterable equality comparisons (closes #101)

## Todos
- [X] Tests
- [X] Documentation
- [X] Examples

### CODE REVIEW

**Comment by nxtSwitch** [comment]
Hi @felangel
Thanks for the prompt solution of the problem!

Can you please tell me if there is a way to solve this problem for manually overriding the `==`? Thanks!

**Comment by felangel** [comment]
Hi @nxtSwitch 👋 

Can you provide a bit more context or a reproduction sample? I'm not sure I understand the use-case/question.

**Comment by felangel** [comment]
@nxtSwitch I believe the reason why that isn't working is because two Iterable instances are considered equal if they have the same elements in the same order. I wouldn't recommend having a custom `Iterable` with a `flag`. Instead it would be good to decouple the two:

```dart
@immutable
class Iterable extends Iterable<String> {
  final List<String> list;

  const IterableWithFlag({this.list});

  @override
  Iterator<String> get iterator => list.iterator;
}

class FlagWrapper<T> {
  final T data;
  final bool flag;

  const FlagWrapper({this.data, this.flag});

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is FlagWrapper<T> && flag == other.flag && data == other.data;
  }
}
```

Hope that helps 👍

**Comment by Tokenyet** [comment]
I might make an issue, but It's maked as fixed, so I can't sure It's my problem or not. I have a test that used equatable but failed on **nested iterable**.

Logs:
```
   Which: at location [0] is ConsoleLine:<ConsoleLine((ConsoleText(null, null, false, 2022-03-01 16:08:51,840 main WARN Advanced terminal features are not available in this environment)))> instead of ConsoleLine:<ConsoleLine([ConsoleText(null, null, false, 2022-03-01 16:08:51,840 main WARN Advanced terminal features are not available in this environment)])>
```

The related classes:
```
class ConsoleLine extends Equatable {
  final Iterable<ConsoleText> texts;
  const ConsoleLine({
    required this.texts,
  });

  ConsoleLine copyWith({
    Iterable<ConsoleText>? texts,
  }) {
    return ConsoleLine(
      texts: texts ?? this.texts,
    );
  }

  @override
  List<Object> get props => [texts];
}

class ConsoleText extends Equatable {
  final Color? foreground;
  final Color? background;
  final bool bold;
  final String text;
  const ConsoleText({
    this.foreground,
    this.background,
    this.bold = false,
    required this.text,
  });

  @override
  List<Object?> get props => [foreground, background, bold, text];

  ConsoleText copyWith({
    Color? foreground,
    Color? background,
    bool? bold,
    String? text,
  }) {
    return ConsoleText(
      foreground: foreground ?? this.foreground,
      background: background ?? this.background,
      bold: bold ?? this.bold,
      text: text ?? this.text,
    );
  }
}
```

The generator method
```
  Iterable<ConsoleLine> parse(String text) sync* {
    final lines = const LineSplitter().convert(text);
    if (lines.isEmpty) return;
    for (final line in lines) {
      final parseResults = decodeAnsiColorEscapeCodes(line, _ansiUp);
      yield ConsoleLine(
        texts: parseResults.map(
          (e) => ConsoleText(
            bold: e.bold,
            text: e.text,
            foreground: _colorFromAnsi(e.fgColor),
            background: _colorFromAnsi(e.bgColor),
          ),
        ),
      );
    }
  }
```

If I change the generator method to the following, the test passed...
```
  Iterable<ConsoleLine> parse(String text) sync* {
    final lines = const LineSplitter().convert(text);
    if (lines.isEmpty) return;
    for (final line in lines) {
      final parseResults = decodeAnsiColorEscapeCodes(line, _ansiUp);
      yield ConsoleLine(
        texts: parseResults.map(
          (e) => ConsoleText(
            bold: e.bold,
            text: e.text,
            foreground: _colorFromAnsi(e.fgColor),
            background: _colorFromAnsi(e.bgColor),
          ),
        ).toList(),
      );
    }
  }
```
Or make the `  List<Object> get props => [texts];` to `  List<Object> get props => [...texts];`, also pass the test. 

Any help would be appreciated!

**Comment by felangel** [comment]
@Tokenyet Equatable should support nested iterable props. I added more tests for this specific case in https://github.com/felangel/equatable/pull/135. Are you able to provide a unit test that fails to illustrate the problem you're facing? Thanks!

**Pull request merged**
